"""Experiment tracking.

The capstone requires runs to be tracked. MLflow is the obvious reach, but it
adds a server, a database and a dependency for something this project needs in
one shape only: an append-only record of what was run, on what data, with what
result, that survives in the repo and can be read without tooling.

So: one JSONL file, one row per run, plus a human-readable leaderboard. Each
run captures the git commit, the dataset fingerprint, the hyperparameters and
the metrics, which is enough to answer the two questions that actually get
asked in a defence -- "which run produced this number?" and "can you get it
again?".

If you later want MLflow, `log_run` is the only function to reimplement.
"""
import hashlib
import json
import platform
import subprocess
import uuid
from datetime import datetime, timezone
from pathlib import Path

from src.config import REPORTS_DIR

RUNS_FILE = REPORTS_DIR / "runs.jsonl"
LEADERBOARD = REPORTS_DIR / "leaderboard.md"


def _git_commit() -> str:
    try:
        out = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                             capture_output=True, text=True, timeout=5)
        if out.returncode == 0:
            dirty = subprocess.run(["git", "status", "--porcelain"],
                                   capture_output=True, text=True, timeout=5).stdout.strip()
            return out.stdout.strip() + ("-dirty" if dirty else "")
    except (OSError, subprocess.SubprocessError):
        pass
    return "unknown"


def dataset_fingerprint(path: Path) -> dict:
    """Identify the exact data a run used.

    A hash rather than a filename: 'dataset.csv' is rebuilt constantly, and two
    runs pointing at the same path can easily have trained on different rows.
    """
    path = Path(path)
    if not path.exists():
        return {"path": str(path), "sha256": None, "rows": None}
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            digest.update(chunk)
    with path.open("r", encoding="utf-8", errors="replace") as fh:
        rows = sum(1 for _ in fh) - 1
    return {"path": str(path), "sha256": digest.hexdigest()[:16], "rows": rows}


def log_run(name: str, params: dict, metrics: dict, dataset: dict = None,
            notes: str = "", artefacts: list = None) -> dict:
    """Append one run to the log and refresh the leaderboard."""
    record = {
        "run_id": uuid.uuid4().hex[:12],
        "name": name,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "git_commit": _git_commit(),
        "python": platform.python_version(),
        "params": params,
        "metrics": metrics,
        "dataset": dataset or {},
        "artefacts": artefacts or [],
        "notes": notes,
    }
    RUNS_FILE.parent.mkdir(parents=True, exist_ok=True)
    with RUNS_FILE.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(record) + "\n")
    write_leaderboard()
    return record


def load_runs() -> list:
    if not RUNS_FILE.exists():
        return []
    runs = []
    for line in RUNS_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            try:
                runs.append(json.loads(line))
            except json.JSONDecodeError:
                continue          # a truncated write must not break reading
    return runs


def write_leaderboard(sort_key: str = "issue_macro_f1") -> Path:
    """Every run, best first. This is the table to put in the report."""
    runs = load_runs()
    lines = [
        "# Experiment log",
        "",
        f"{len(runs)} run(s). Generated by `src.training.tracking`; do not edit by hand.",
        "",
        "| Run | Model | Sentiment macro-F1 | Issue macro-F1 | Issue micro-F1 | Rows | Data | Commit | When |",
        "|---|---|---|---|---|---|---|---|---|",
    ]

    def key(r):
        v = r.get("metrics", {}).get(sort_key)
        return v if isinstance(v, (int, float)) else -1

    for r in sorted(runs, key=key, reverse=True):
        m = r.get("metrics", {})
        fmt = lambda v: f"{v:.4f}" if isinstance(v, (int, float)) else "—"
        lines.append(
            f"| `{r['run_id']}` | {r['name']} | {fmt(m.get('sentiment_macro_f1'))} "
            f"| {fmt(m.get('issue_macro_f1'))} | {fmt(m.get('issue_micro_f1'))} "
            f"| {r.get('dataset', {}).get('rows') or '—'} "
            f"| `{r.get('dataset', {}).get('sha256') or '—'}` "
            f"| `{r.get('git_commit', '—')}` | {r['timestamp'][:16].replace('T', ' ')} |"
        )

    if any(r.get("notes") for r in runs):
        lines += ["", "## Notes", ""]
        for r in runs:
            if r.get("notes"):
                lines.append(f"- `{r['run_id']}` — {r['notes']}")

    lines += [
        "",
        "## Reading this table",
        "",
        "Sentiment macro-F1 leads over accuracy because positive reviews dominate; "
        "a model that always answers \"positive\" scores well on accuracy and badly here.",
        "",
        "Issue macro-F1 averages over categories, so a rare-but-expensive category "
        "(defects) counts as much as a common one. Per-category numbers, including which "
        "labels were too rare to score reliably, are in the matching `*_report.json`.",
        "",
        "**Two runs are only comparable when the `Data` hash matches.** A different hash "
        "means different rows, and the numbers are not measuring the same thing.",
    ]

    LEADERBOARD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return LEADERBOARD


def summarise_for_tracking(report: dict) -> dict:
    """Pull the headline numbers out of a full evaluation report."""
    sentiment = report.get("sentiment", {})
    issues = report.get("issues_summary", {})
    return {
        "sentiment_accuracy": sentiment.get("accuracy"),
        "sentiment_macro_f1": sentiment.get("macro_f1"),
        "issue_macro_f1": issues.get("macro_f1"),
        "issue_micro_f1": issues.get("micro_f1"),
        "issue_macro_f1_excluding_rare": issues.get("macro_f1_excluding_rare"),
        "issue_threshold": issues.get("threshold"),
        "exact_match_ratio": issues.get("exact_match_ratio"),
    }
